// Code generated by ent, DO NOT EDIT.

package devicehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the devicehistory type in the database.
	Label = "device_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeviceUUID holds the string denoting the device_uuid field in the database.
	FieldDeviceUUID = "device_uuid"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldHistoryTag holds the string denoting the history_tag field in the database.
	FieldHistoryTag = "history_tag"
	// FieldRecordID holds the string denoting the record_id field in the database.
	FieldRecordID = "record_id"
	// FieldParameter holds the string denoting the parameter field in the database.
	FieldParameter = "parameter"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the devicehistory in the database.
	Table = "device_histories"
)

// Columns holds all SQL columns for devicehistory fields.
var Columns = []string{
	FieldID,
	FieldDeviceUUID,
	FieldEventType,
	FieldTimestamp,
	FieldHistoryTag,
	FieldRecordID,
	FieldParameter,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the DeviceHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeviceUUID orders the results by the device_uuid field.
func ByDeviceUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceUUID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByHistoryTag orders the results by the history_tag field.
func ByHistoryTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHistoryTag, opts...).ToFunc()
}

// ByRecordID orders the results by the record_id field.
func ByRecordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordID, opts...).ToFunc()
}

// ByParameter orders the results by the parameter field.
func ByParameter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParameter, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
