// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DeviceStatusColumns holds the columns for the "device_status" table.
	DeviceStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "battery_percentage", Type: field.TypeInt},
		{Name: "battery_voltage", Type: field.TypeFloat64},
		{Name: "position", Type: field.TypeInt},
		{Name: "status", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// DeviceStatusTable holds the schema information for the "device_status" table.
	DeviceStatusTable = &schema.Table{
		Name:       "device_status",
		Columns:    DeviceStatusColumns,
		PrimaryKey: []*schema.Column{DeviceStatusColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DeviceStatusTable,
	}
)

func init() {
}
