// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/cateiru/sesami-2-mackerel/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/cateiru/sesami-2-mackerel/ent/devicehistory"
	"github.com/cateiru/sesami-2-mackerel/ent/devicestatus"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DeviceHistory is the client for interacting with the DeviceHistory builders.
	DeviceHistory *DeviceHistoryClient
	// DeviceStatus is the client for interacting with the DeviceStatus builders.
	DeviceStatus *DeviceStatusClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.DeviceHistory = NewDeviceHistoryClient(c.config)
	c.DeviceStatus = NewDeviceStatusClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		DeviceHistory: NewDeviceHistoryClient(cfg),
		DeviceStatus:  NewDeviceStatusClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		DeviceHistory: NewDeviceHistoryClient(cfg),
		DeviceStatus:  NewDeviceStatusClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DeviceHistory.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.DeviceHistory.Use(hooks...)
	c.DeviceStatus.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.DeviceHistory.Intercept(interceptors...)
	c.DeviceStatus.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DeviceHistoryMutation:
		return c.DeviceHistory.mutate(ctx, m)
	case *DeviceStatusMutation:
		return c.DeviceStatus.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DeviceHistoryClient is a client for the DeviceHistory schema.
type DeviceHistoryClient struct {
	config
}

// NewDeviceHistoryClient returns a client for the DeviceHistory from the given config.
func NewDeviceHistoryClient(c config) *DeviceHistoryClient {
	return &DeviceHistoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `devicehistory.Hooks(f(g(h())))`.
func (c *DeviceHistoryClient) Use(hooks ...Hook) {
	c.hooks.DeviceHistory = append(c.hooks.DeviceHistory, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `devicehistory.Intercept(f(g(h())))`.
func (c *DeviceHistoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.DeviceHistory = append(c.inters.DeviceHistory, interceptors...)
}

// Create returns a builder for creating a DeviceHistory entity.
func (c *DeviceHistoryClient) Create() *DeviceHistoryCreate {
	mutation := newDeviceHistoryMutation(c.config, OpCreate)
	return &DeviceHistoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DeviceHistory entities.
func (c *DeviceHistoryClient) CreateBulk(builders ...*DeviceHistoryCreate) *DeviceHistoryCreateBulk {
	return &DeviceHistoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceHistoryClient) MapCreateBulk(slice any, setFunc func(*DeviceHistoryCreate, int)) *DeviceHistoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceHistoryCreateBulk{err: fmt.Errorf("calling to DeviceHistoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceHistoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceHistoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DeviceHistory.
func (c *DeviceHistoryClient) Update() *DeviceHistoryUpdate {
	mutation := newDeviceHistoryMutation(c.config, OpUpdate)
	return &DeviceHistoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceHistoryClient) UpdateOne(_m *DeviceHistory) *DeviceHistoryUpdateOne {
	mutation := newDeviceHistoryMutation(c.config, OpUpdateOne, withDeviceHistory(_m))
	return &DeviceHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceHistoryClient) UpdateOneID(id int) *DeviceHistoryUpdateOne {
	mutation := newDeviceHistoryMutation(c.config, OpUpdateOne, withDeviceHistoryID(id))
	return &DeviceHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DeviceHistory.
func (c *DeviceHistoryClient) Delete() *DeviceHistoryDelete {
	mutation := newDeviceHistoryMutation(c.config, OpDelete)
	return &DeviceHistoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceHistoryClient) DeleteOne(_m *DeviceHistory) *DeviceHistoryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceHistoryClient) DeleteOneID(id int) *DeviceHistoryDeleteOne {
	builder := c.Delete().Where(devicehistory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceHistoryDeleteOne{builder}
}

// Query returns a query builder for DeviceHistory.
func (c *DeviceHistoryClient) Query() *DeviceHistoryQuery {
	return &DeviceHistoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeviceHistory},
		inters: c.Interceptors(),
	}
}

// Get returns a DeviceHistory entity by its id.
func (c *DeviceHistoryClient) Get(ctx context.Context, id int) (*DeviceHistory, error) {
	return c.Query().Where(devicehistory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceHistoryClient) GetX(ctx context.Context, id int) *DeviceHistory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceHistoryClient) Hooks() []Hook {
	return c.hooks.DeviceHistory
}

// Interceptors returns the client interceptors.
func (c *DeviceHistoryClient) Interceptors() []Interceptor {
	return c.inters.DeviceHistory
}

func (c *DeviceHistoryClient) mutate(ctx context.Context, m *DeviceHistoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceHistoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceHistoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceHistoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DeviceHistory mutation op: %q", m.Op())
	}
}

// DeviceStatusClient is a client for the DeviceStatus schema.
type DeviceStatusClient struct {
	config
}

// NewDeviceStatusClient returns a client for the DeviceStatus from the given config.
func NewDeviceStatusClient(c config) *DeviceStatusClient {
	return &DeviceStatusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `devicestatus.Hooks(f(g(h())))`.
func (c *DeviceStatusClient) Use(hooks ...Hook) {
	c.hooks.DeviceStatus = append(c.hooks.DeviceStatus, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `devicestatus.Intercept(f(g(h())))`.
func (c *DeviceStatusClient) Intercept(interceptors ...Interceptor) {
	c.inters.DeviceStatus = append(c.inters.DeviceStatus, interceptors...)
}

// Create returns a builder for creating a DeviceStatus entity.
func (c *DeviceStatusClient) Create() *DeviceStatusCreate {
	mutation := newDeviceStatusMutation(c.config, OpCreate)
	return &DeviceStatusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DeviceStatus entities.
func (c *DeviceStatusClient) CreateBulk(builders ...*DeviceStatusCreate) *DeviceStatusCreateBulk {
	return &DeviceStatusCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DeviceStatusClient) MapCreateBulk(slice any, setFunc func(*DeviceStatusCreate, int)) *DeviceStatusCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DeviceStatusCreateBulk{err: fmt.Errorf("calling to DeviceStatusClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DeviceStatusCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DeviceStatusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DeviceStatus.
func (c *DeviceStatusClient) Update() *DeviceStatusUpdate {
	mutation := newDeviceStatusMutation(c.config, OpUpdate)
	return &DeviceStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DeviceStatusClient) UpdateOne(_m *DeviceStatus) *DeviceStatusUpdateOne {
	mutation := newDeviceStatusMutation(c.config, OpUpdateOne, withDeviceStatus(_m))
	return &DeviceStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DeviceStatusClient) UpdateOneID(id int) *DeviceStatusUpdateOne {
	mutation := newDeviceStatusMutation(c.config, OpUpdateOne, withDeviceStatusID(id))
	return &DeviceStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DeviceStatus.
func (c *DeviceStatusClient) Delete() *DeviceStatusDelete {
	mutation := newDeviceStatusMutation(c.config, OpDelete)
	return &DeviceStatusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DeviceStatusClient) DeleteOne(_m *DeviceStatus) *DeviceStatusDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DeviceStatusClient) DeleteOneID(id int) *DeviceStatusDeleteOne {
	builder := c.Delete().Where(devicestatus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DeviceStatusDeleteOne{builder}
}

// Query returns a query builder for DeviceStatus.
func (c *DeviceStatusClient) Query() *DeviceStatusQuery {
	return &DeviceStatusQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeviceStatus},
		inters: c.Interceptors(),
	}
}

// Get returns a DeviceStatus entity by its id.
func (c *DeviceStatusClient) Get(ctx context.Context, id int) (*DeviceStatus, error) {
	return c.Query().Where(devicestatus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DeviceStatusClient) GetX(ctx context.Context, id int) *DeviceStatus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DeviceStatusClient) Hooks() []Hook {
	return c.hooks.DeviceStatus
}

// Interceptors returns the client interceptors.
func (c *DeviceStatusClient) Interceptors() []Interceptor {
	return c.inters.DeviceStatus
}

func (c *DeviceStatusClient) mutate(ctx context.Context, m *DeviceStatusMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DeviceStatusCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DeviceStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DeviceStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DeviceStatusDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DeviceStatus mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		DeviceHistory, DeviceStatus []ent.Hook
	}
	inters struct {
		DeviceHistory, DeviceStatus []ent.Interceptor
	}
)
