// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cateiru/sesami-2-mackerel/ent/devicehistory"
)

// DeviceHistoryCreate is the builder for creating a DeviceHistory entity.
type DeviceHistoryCreate struct {
	config
	mutation *DeviceHistoryMutation
	hooks    []Hook
}

// SetDeviceUUID sets the "device_uuid" field.
func (_c *DeviceHistoryCreate) SetDeviceUUID(v string) *DeviceHistoryCreate {
	_c.mutation.SetDeviceUUID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *DeviceHistoryCreate) SetEventType(v string) *DeviceHistoryCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *DeviceHistoryCreate) SetTimestamp(v int64) *DeviceHistoryCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DeviceHistoryCreate) SetUserID(v string) *DeviceHistoryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *DeviceHistoryCreate) SetNillableUserID(v *string) *DeviceHistoryCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetTag sets the "tag" field.
func (_c *DeviceHistoryCreate) SetTag(v string) *DeviceHistoryCreate {
	_c.mutation.SetTag(v)
	return _c
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_c *DeviceHistoryCreate) SetNillableTag(v *string) *DeviceHistoryCreate {
	if v != nil {
		_c.SetTag(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceHistoryCreate) SetCreatedAt(v time.Time) *DeviceHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceHistoryCreate) SetNillableCreatedAt(v *time.Time) *DeviceHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the DeviceHistoryMutation object of the builder.
func (_c *DeviceHistoryCreate) Mutation() *DeviceHistoryMutation {
	return _c.mutation
}

// Save creates the DeviceHistory in the database.
func (_c *DeviceHistoryCreate) Save(ctx context.Context) (*DeviceHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceHistoryCreate) SaveX(ctx context.Context) *DeviceHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceHistoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := devicehistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceHistoryCreate) check() error {
	if _, ok := _c.mutation.DeviceUUID(); !ok {
		return &ValidationError{Name: "device_uuid", err: errors.New(`ent: missing required field "DeviceHistory.device_uuid"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "DeviceHistory.event_type"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "DeviceHistory.timestamp"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceHistory.created_at"`)}
	}
	return nil
}

func (_c *DeviceHistoryCreate) sqlSave(ctx context.Context) (*DeviceHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceHistoryCreate) createSpec() (*DeviceHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(devicehistory.Table, sqlgraph.NewFieldSpec(devicehistory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeviceUUID(); ok {
		_spec.SetField(devicehistory.FieldDeviceUUID, field.TypeString, value)
		_node.DeviceUUID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(devicehistory.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(devicehistory.FieldTimestamp, field.TypeInt64, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(devicehistory.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Tag(); ok {
		_spec.SetField(devicehistory.FieldTag, field.TypeString, value)
		_node.Tag = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(devicehistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DeviceHistoryCreateBulk is the builder for creating many DeviceHistory entities in bulk.
type DeviceHistoryCreateBulk struct {
	config
	err      error
	builders []*DeviceHistoryCreate
}

// Save creates the DeviceHistory entities in the database.
func (_c *DeviceHistoryCreateBulk) Save(ctx context.Context) ([]*DeviceHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeviceHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceHistoryCreateBulk) SaveX(ctx context.Context) []*DeviceHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
