// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cateiru/sesami-2-mackerel/ent/devicehistory"
	"github.com/cateiru/sesami-2-mackerel/ent/predicate"
)

// DeviceHistoryDelete is the builder for deleting a DeviceHistory entity.
type DeviceHistoryDelete struct {
	config
	hooks    []Hook
	mutation *DeviceHistoryMutation
}

// Where appends a list predicates to the DeviceHistoryDelete builder.
func (_d *DeviceHistoryDelete) Where(ps ...predicate.DeviceHistory) *DeviceHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DeviceHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeviceHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DeviceHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(devicehistory.Table, sqlgraph.NewFieldSpec(devicehistory.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DeviceHistoryDeleteOne is the builder for deleting a single DeviceHistory entity.
type DeviceHistoryDeleteOne struct {
	_d *DeviceHistoryDelete
}

// Where appends a list predicates to the DeviceHistoryDelete builder.
func (_d *DeviceHistoryDeleteOne) Where(ps ...predicate.DeviceHistory) *DeviceHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DeviceHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{devicehistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeviceHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
