// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cateiru/sesami-2-mackerel/ent/devicestatus"
)

// DeviceStatusCreate is the builder for creating a DeviceStatus entity.
type DeviceStatusCreate struct {
	config
	mutation *DeviceStatusMutation
	hooks    []Hook
}

// SetBatteryPercentage sets the "battery_percentage" field.
func (_c *DeviceStatusCreate) SetBatteryPercentage(v int) *DeviceStatusCreate {
	_c.mutation.SetBatteryPercentage(v)
	return _c
}

// SetWm2State sets the "wm2_state" field.
func (_c *DeviceStatusCreate) SetWm2State(v bool) *DeviceStatusCreate {
	_c.mutation.SetWm2State(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DeviceStatusCreate) SetStatus(v string) *DeviceStatusCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *DeviceStatusCreate) SetTimestamp(v int64) *DeviceStatusCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceStatusCreate) SetCreatedAt(v time.Time) *DeviceStatusCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceStatusCreate) SetNillableCreatedAt(v *time.Time) *DeviceStatusCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the DeviceStatusMutation object of the builder.
func (_c *DeviceStatusCreate) Mutation() *DeviceStatusMutation {
	return _c.mutation
}

// Save creates the DeviceStatus in the database.
func (_c *DeviceStatusCreate) Save(ctx context.Context) (*DeviceStatus, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceStatusCreate) SaveX(ctx context.Context) *DeviceStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceStatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceStatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceStatusCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := devicestatus.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceStatusCreate) check() error {
	if _, ok := _c.mutation.BatteryPercentage(); !ok {
		return &ValidationError{Name: "battery_percentage", err: errors.New(`ent: missing required field "DeviceStatus.battery_percentage"`)}
	}
	if _, ok := _c.mutation.Wm2State(); !ok {
		return &ValidationError{Name: "wm2_state", err: errors.New(`ent: missing required field "DeviceStatus.wm2_state"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DeviceStatus.status"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "DeviceStatus.timestamp"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceStatus.created_at"`)}
	}
	return nil
}

func (_c *DeviceStatusCreate) sqlSave(ctx context.Context) (*DeviceStatus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceStatusCreate) createSpec() (*DeviceStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceStatus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(devicestatus.Table, sqlgraph.NewFieldSpec(devicestatus.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.BatteryPercentage(); ok {
		_spec.SetField(devicestatus.FieldBatteryPercentage, field.TypeInt, value)
		_node.BatteryPercentage = value
	}
	if value, ok := _c.mutation.Wm2State(); ok {
		_spec.SetField(devicestatus.FieldWm2State, field.TypeBool, value)
		_node.Wm2State = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(devicestatus.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(devicestatus.FieldTimestamp, field.TypeInt64, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(devicestatus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DeviceStatusCreateBulk is the builder for creating many DeviceStatus entities in bulk.
type DeviceStatusCreateBulk struct {
	config
	err      error
	builders []*DeviceStatusCreate
}

// Save creates the DeviceStatus entities in the database.
func (_c *DeviceStatusCreateBulk) Save(ctx context.Context) ([]*DeviceStatus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeviceStatus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceStatusCreateBulk) SaveX(ctx context.Context) []*DeviceStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceStatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
