// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cateiru/sesami-2-mackerel/ent/devicestatus"
)

// DeviceStatus is the model entity for the DeviceStatus schema.
type DeviceStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// バッテリー残量（%）
	BatteryPercentage int `json:"battery_percentage,omitempty"`
	// Wm2State holds the value of the "wm2_state" field.
	Wm2State bool `json:"wm2_state,omitempty"`
	// デバイスステータス
	Status string `json:"status,omitempty"`
	// SESAMI APIからのタイムスタンプ
	Timestamp int64 `json:"timestamp,omitempty"`
	// レコード作成日時
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeviceStatus) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case devicestatus.FieldWm2State:
			values[i] = new(sql.NullBool)
		case devicestatus.FieldID, devicestatus.FieldBatteryPercentage, devicestatus.FieldTimestamp:
			values[i] = new(sql.NullInt64)
		case devicestatus.FieldStatus:
			values[i] = new(sql.NullString)
		case devicestatus.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeviceStatus fields.
func (_m *DeviceStatus) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case devicestatus.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case devicestatus.FieldBatteryPercentage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field battery_percentage", values[i])
			} else if value.Valid {
				_m.BatteryPercentage = int(value.Int64)
			}
		case devicestatus.FieldWm2State:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field wm2_state", values[i])
			} else if value.Valid {
				_m.Wm2State = value.Bool
			}
		case devicestatus.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case devicestatus.FieldTimestamp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Int64
			}
		case devicestatus.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeviceStatus.
// This includes values selected through modifiers, order, etc.
func (_m *DeviceStatus) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DeviceStatus.
// Note that you need to call DeviceStatus.Unwrap() before calling this method if this DeviceStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeviceStatus) Update() *DeviceStatusUpdateOne {
	return NewDeviceStatusClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeviceStatus entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeviceStatus) Unwrap() *DeviceStatus {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeviceStatus is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeviceStatus) String() string {
	var builder strings.Builder
	builder.WriteString("DeviceStatus(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("battery_percentage=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatteryPercentage))
	builder.WriteString(", ")
	builder.WriteString("wm2_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.Wm2State))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(fmt.Sprintf("%v", _m.Timestamp))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeviceStatusSlice is a parsable slice of DeviceStatus.
type DeviceStatusSlice []*DeviceStatus
