// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cateiru/sesami-2-mackerel/ent/devicestatus"
	"github.com/cateiru/sesami-2-mackerel/ent/predicate"
)

// DeviceStatusDelete is the builder for deleting a DeviceStatus entity.
type DeviceStatusDelete struct {
	config
	hooks    []Hook
	mutation *DeviceStatusMutation
}

// Where appends a list predicates to the DeviceStatusDelete builder.
func (_d *DeviceStatusDelete) Where(ps ...predicate.DeviceStatus) *DeviceStatusDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DeviceStatusDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeviceStatusDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DeviceStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(devicestatus.Table, sqlgraph.NewFieldSpec(devicestatus.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DeviceStatusDeleteOne is the builder for deleting a single DeviceStatus entity.
type DeviceStatusDeleteOne struct {
	_d *DeviceStatusDelete
}

// Where appends a list predicates to the DeviceStatusDelete builder.
func (_d *DeviceStatusDeleteOne) Where(ps ...predicate.DeviceStatus) *DeviceStatusDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DeviceStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{devicestatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeviceStatusDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
