// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/cateiru/sesami-2-mackerel/ent/devicestatus"
	"github.com/cateiru/sesami-2-mackerel/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	devicestatusFields := schema.DeviceStatus{}.Fields()
	_ = devicestatusFields
	// devicestatusDescCreatedAt is the schema descriptor for created_at field.
	devicestatusDescCreatedAt := devicestatusFields[5].Descriptor()
	// devicestatus.DefaultCreatedAt holds the default value on creation for the created_at field.
	devicestatus.DefaultCreatedAt = devicestatusDescCreatedAt.Default.(func() time.Time)
}
