// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DeviceHistory is the predicate function for devicehistory builders.
type DeviceHistory func(*sql.Selector)

// DeviceStatus is the predicate function for devicestatus builders.
type DeviceStatus func(*sql.Selector)
